version: '3.1'
services: 
  admin:
    build: ../admin
    ports:
      - 8280:8080
  users:
    build: ../users
    ports:
      - 8281:8080
  todos:
    build: ../todos
    ports:
      - 8282:8080
  www:
    build: ../www
    ports:
      - 8380:80